//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adgw.DacsUserDelete {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.mobilengine.com/Wdx")]
    public partial class EnqueueDacsFail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private string dacsidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dacsid {
            get {
                return this.dacsidField;
            }
            set {
                this.dacsidField = value;
                this.RaisePropertyChanged("dacsid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.mobilengine.com/Wdx")]
    public partial class DacsContent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private user itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("user", Namespace="http://mobilengine.com/adgw/user-delete", Order=0)]
        public user Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mobilengine.com/adgw/user-delete")]
    public partial class user : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string adGuidField;
        
        private string usernField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string adGuid {
            get {
                return this.adGuidField;
            }
            set {
                this.adGuidField = value;
                this.RaisePropertyChanged("adGuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string usern {
            get {
                return this.usernField;
            }
            set {
                this.usernField = value;
                this.RaisePropertyChanged("usern");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.mobilengine.com/Wdx")]
    public partial class Dacs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private DacsContent contentField;
        
        private string dacsidField;
        
        private System.DateTime dtuField;
        
        private DacsMeta metaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DacsContent Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("Content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dacsid {
            get {
                return this.dacsidField;
            }
            set {
                this.dacsidField = value;
                this.RaisePropertyChanged("dacsid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dtu {
            get {
                return this.dtuField;
            }
            set {
                this.dtuField = value;
                this.RaisePropertyChanged("dtu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DacsMeta meta {
            get {
                return this.metaField;
            }
            set {
                this.metaField = value;
                this.RaisePropertyChanged("meta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.mobilengine.com/Wdx")]
    public enum DacsMeta {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("user-delete")]
        userdelete,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.mobilengine.com/Wdx", ConfigurationName="DacsUserDelete.IWdx")]
    public interface IWdx {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.mobilengine.com/Wdx/IWdx/EnqueueDacs", ReplyAction="http://schemas.mobilengine.com/Wdx/IWdx/EnqueueDacsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Adgw.DacsUserDelete.EnqueueDacsFail), Action="http://schemas.mobilengine.com/Wdx/IWdx/EnqueueDacsEnqueueDacsFailFault", Name="EnqueueDacsFail")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void EnqueueDacs(Adgw.DacsUserDelete.Dacs dacs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.mobilengine.com/Wdx/IWdx/EnqueueDacs", ReplyAction="http://schemas.mobilengine.com/Wdx/IWdx/EnqueueDacsResponse")]
        System.Threading.Tasks.Task EnqueueDacsAsync(Adgw.DacsUserDelete.Dacs dacs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWdxChannel : Adgw.DacsUserDelete.IWdx, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WdxClient : System.ServiceModel.ClientBase<Adgw.DacsUserDelete.IWdx>, Adgw.DacsUserDelete.IWdx {
        
        public WdxClient() {
        }
        
        public WdxClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WdxClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WdxClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WdxClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void EnqueueDacs(Adgw.DacsUserDelete.Dacs dacs) {
            base.Channel.EnqueueDacs(dacs);
        }
        
        public System.Threading.Tasks.Task EnqueueDacsAsync(Adgw.DacsUserDelete.Dacs dacs) {
            return base.Channel.EnqueueDacsAsync(dacs);
        }
    }
}
