
package com.mobilengine.schemas.wdx;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "EnqueueDacsFail", targetNamespace = "http://schemas.mobilengine.com/Wdx")
public class IWdxEnqueueDacsEnqueueDacsFailFaultFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EnqueueDacsFail faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public IWdxEnqueueDacsEnqueueDacsFailFaultFaultMessage(String message, EnqueueDacsFail faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public IWdxEnqueueDacsEnqueueDacsFailFaultFaultMessage(String message, EnqueueDacsFail faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.mobilengine.schemas.wdx.EnqueueDacsFail
     */
    public EnqueueDacsFail getFaultInfo() {
        return faultInfo;
    }

}
