
package com.mobilengine.schemas.wdx;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IWdx", targetNamespace = "http://schemas.mobilengine.com/Wdx")
@XmlSeeAlso({
    com.mobilengine.schemas.wdx.ObjectFactory.class,
    generated.ObjectFactory.class
})
public interface IWdx {


    /**
     * 
     * @param dacs
     * @throws IWdxEnqueueDacsEnqueueDacsFailFaultFaultMessage
     */
    @WebMethod(operationName = "EnqueueDacs", action = "http://schemas.mobilengine.com/Wdx/IWdx/EnqueueDacs")
    @RequestWrapper(localName = "EnqueueDacs", targetNamespace = "http://schemas.mobilengine.com/Wdx", className = "com.mobilengine.schemas.wdx.EnqueueDacs")
    @ResponseWrapper(localName = "EnqueueDacsResponse", targetNamespace = "http://schemas.mobilengine.com/Wdx", className = "com.mobilengine.schemas.wdx.EnqueueDacsResponse")
    public void enqueueDacs(
        @WebParam(name = "dacs", targetNamespace = "http://schemas.mobilengine.com/Wdx")
        Dacs dacs)
        throws IWdxEnqueueDacsEnqueueDacsFailFaultFaultMessage
    ;

}
