
package com.mobilengine.schemas.wdx;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Wdx", targetNamespace = "http://schemas.mobilengine.com/Wdx", wsdlLocation = "file:/C:/Work/MobileEngine/samples/s18/MobilengineIntegration/java/TestClient/src/main/resources/purchase-order.wsdl")
public class Wdx
    extends Service
{

    private final static URL WDX_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.mobilengine.schemas.wdx.Wdx.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.mobilengine.schemas.wdx.Wdx.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Work/MobileEngine/samples/s18/MobilengineIntegration/java/TestClient/src/main/resources/purchase-order.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Work/MobileEngine/samples/s18/MobilengineIntegration/java/TestClient/src/main/resources/purchase-order.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WDX_WSDL_LOCATION = url;
    }

    public Wdx(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Wdx() {
        super(WDX_WSDL_LOCATION, new QName("http://schemas.mobilengine.com/Wdx", "Wdx"));
    }

    /**
     * 
     * @return
     *     returns IWdx
     */
    @WebEndpoint(name = "BasicHttpBinding_IWdx")
    public IWdx getBasicHttpBindingIWdx() {
        return super.getPort(new QName("http://schemas.mobilengine.com/Wdx", "BasicHttpBinding_IWdx"), IWdx.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWdx
     */
    @WebEndpoint(name = "BasicHttpBinding_IWdx")
    public IWdx getBasicHttpBindingIWdx(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.mobilengine.com/Wdx", "BasicHttpBinding_IWdx"), IWdx.class, features);
    }

}
